spring:
  application:
    name: auth-service
    security:
      jwt:
        access-key:
          value: ${ACCESS_KEY}
          expiration-time: 10
        refresh-key:
          value: ${REFRESH_KEY}
          expiration-time: 120
      api-key: ${API_KEY}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-auth-master.yaml
    enabled: true
    default-schema: auth_service_schema
  datasource:
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/}${DATABASE_NAME:barber-shop-database}
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    properties:
      hibernate:
        show_sql: true
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always



feign:
  clients:
    user-service:
      url: ${USER_SERVICE_URL}
