spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/barber-shop-database
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: false