services:

#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.10.2
#    container_name: kibana
#    ports:
#      - "5601:5601"
#    environment:
#      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
#      - "SERVER_HOST=0.0.0.0"
#      - "ELASTICSEARCH_USERNAME=kibana_system"
#      - "ELASTICSEARCH_PASSWORD=_rI6ySgpfznuLMUdSBS0"
#      - "ELASTICSEARCH_SSL_VERIFICATIONMODE=none"
#    networks:
#      - plahctoh
#
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
#    container_name: elasticsearch
#    environment:
#      - "discovery.type=single-node"
#      - "ELASTIC_PASSWORD=XNV1iC2BZ7alheRmqo1_"
#      - "xpack.security.enabled=false"
#    ports:
#      - "9200:9200"
#    mem_limit: 2g
#    mem_reservation: 1g
#    healthcheck:
#      test: [ "CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health | grep green || exit 1" ]
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 30s
#    networks:
#      - plahctoh
#
#  logstash:
#    image: docker.elastic.co/logstash/logstash:8.16.1
#    container_name: logstash
#    user: "0:0"
#    depends_on:
#      elasticsearch:
#        condition: service_healthy
#    ports:
#      - "5044:5044"
#      - "9600:9600"
#    volumes:
#      - ./logstash/config:/usr/share/logstash/config
#      - ./logstash/pipeline:/usr/share/logstash/pipeline
#      - ./logs:/app/logs
#    environment:
#      - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "LOGSTASH_DISABLE_ES_PING=true"
#      - "xpack.monitoring.elasticsearch.hosts=http://elasticsearch:9200"
#      - "xpack.monitoring.elasticsearch.username=elastic"
#      - "xpack.monitoring.elasticsearch.password=XNV1iC2BZ7alheRmqo1_"
#      - "xpack.monitoring.enabled=true"
#    networks:
#      - plahctoh


  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.4
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - plahctoh

  plahctoh-database:
    image: postgres:14.7-alpine
    env_file:
      - env/datasource.env
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "plahctoh-database" ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - "./db/init-scripts:/docker-entrypoint-initdb.d/"
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - plahctoh

  pgadmin-ui:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      plahctoh-database:
        condition: service_healthy
    ports:
      - "5051:80"
    env_file:
      - env/datasource.env
    networks:
      - plahctoh
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  kafka:
    image: confluentinc/cp-kafka:6.2.4
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9092 --list
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: OUTSIDE://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://localhost:29092,INTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - plahctoh

  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - plahctoh

  auth-service:
    #    image: quay.io/keycloak/keycloak:26.0.4
    build: ./auth-service
    healthcheck:
      test: curl -f http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always
    env_file:
      - env/security.env
      - env/feign-services-url.env
      - env/datasource.env
    #      - env/keycloak.env
    depends_on:
      user-service:
        condition: service_healthy
    #    command:
    #      - start-dev
    networks:
      - plahctoh

  notification-service:
    build: ./notification-service
    healthcheck:
      test: curl -f http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
    depends_on:
      kafka-topics-generator:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
      auth-service:
        condition: service_started
    volumes:
      - ./logs:/app/logs
    environment:
      - LOG_PATH=/app/logs/service.log
    networks:
      - plahctoh

  booking-service:
    build: ./booking-service
    healthcheck:
      test: curl -f http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    env_file:
      - env/security.env
      - env/datasource.env
      - env/feign-services-url.env
    restart: always
    depends_on:
      #      kafka-topics-generator:
      #        condition: service_completed_successfully
      #      kafka:
      #        condition: service_healthy
      auth-service:
        condition: service_started
    networks:
      - plahctoh

  user-service:
    build: ./user-service
    healthcheck:
      test: curl -f http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    env_file:
      - env/datasource.env
      - env/security.env
    depends_on:
      plahctoh-database:
        condition: service_healthy
    networks:
      - plahctoh

  account-service:
    build: ./account-service
    healthcheck:
      test: curl -f http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    env_file:
      - env/datasource.env
      - env/security.env
      - env/feign-services-url.env
    depends_on:
      user-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    networks:
      - plahctoh

  calendar-service:
    build: ./calendar-service
    healthcheck:
      test: curl -f http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    env_file:
      - env/security.env
      - env/datasource.env
    depends_on:
      plahctoh-database:
        condition: service_healthy
    networks:
      - plahctoh

  gateway-service:
    build: ./gateway-service
    ports:
      - "7080:8080"
    healthcheck:
      test: curl -f http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always
    env_file:
      - env/feign-services-url.env
      - env/security.env
      - env/keycloak.env
    networks:
      - plahctoh

  kafka-topics-generator:
    image: confluentinc/cp-kafka:6.2.4
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: [ '/bin/sh', '-c' ]
    networks:
      - plahctoh
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:9092 --list

      # echo -e 'Creating kafka topics'
       kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic notification-topic --replication-factor 1 --partitions 3
      # kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic order-topic --replication-factor 1 --partitions 3

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      "

networks:
  plahctoh:
    driver: bridge

volumes:
  local_pgdata:
  pgadmin_data: