spring:
  application:
    name: "calendar-service"
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-calendar-master.yaml
    enabled: true
    default-schema: "calendar_service_schema"
  datasource:
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/}${DATABASE_NAME:plahctoh-database}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always