spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  application:
    name: booking-service
    domain: ${APPLICATION_DOMAIN:"http://localhost:7080"}
    security:
      jwt:
        access-key:
          value: ${ACCESS_KEY}
          expiration-time: 10
        refresh-key:
          value: ${REFRESH_KEY}
          expiration-time: 120
      api-key: ${API_KEY}
    booking:
      time-slot:
        booking-start-time:
          value: ${BOOKING_TIME_START}
        booking-end-time:
          value: ${BOOKING_TIME_END}
        time-slot-duration:
          value: ${TIME_SLOT_DURATION}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-booking-master.yaml
    enabled: true
    default-schema: "booking_service_schema"
  datasource:
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/}${DATABASE_NAME:plahctoh-database}
    hikari:
      schema: "booking_service_schema"
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    properties:
      hibernate:
        show_sql: true
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

feign:
  clients:
    auth-service:
      url: ${AUTH_SERVICE_URL}
    department-service:
      url: ${DEPARTMENT_SERVICE_URL}
    user-service:
      url: ${USER_SERVICE_URL}