package eu.senla.common.enums;

public enum PermissionValue {

    CREATE_USER, ADD_PERMISSION, REMOVE_PERMISSION, VIEW_ACCOUNT, EDIT_ACCOUNT, CREATE_BOOKING, VIEW_SELF_BOOKINGS,
    VIEW_BOOKINGS, CREATE_PROCEDURE, DELETE_PROCEDURE, EDIT_PROCEDURE, SELF_ASSIGN_ON_PROCEDURE, VIEW_PROCEDURE,
    EDIT_USER, VIEW_USER, VIEW_PERMISSIONS, VIEW_SELF_PERMISSIONS, VIEW_USER_ACCOUNTS
}
