spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8082/realms/barbershop-realm}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8082/realms/barbershop-realm/protocol/openid-connect/certs}
  cloud:
    gateway:
      mvc:
        routes:
          - id: notification-route
            uri: http://localhost:8081
            ## use this uri inside of docker compose
            ## uri: http://notification-service:8080
            predicates:
              - Path=/notifications

jwt:
  auth:
    converter:
      resource-id: barbershop-realm




