spring:
  application:
    name: gateway-service
    #  security:
    #    oauth2:
    #      resourceserver:
    #        jwt:
    #          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8082/realms/plahctoh-realm}
    #          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8082/realms/plahctoh-realm/protocol/openid-connect/certs}
    security:
      jwt:
        access-key:
          expiration-time: 10
        refresh-key:
          expiration-time: 120
  cloud:
    gateway:
      mvc:
        routes:
          # Auth Service
          - id: auth-service-route
            uri: http://auth-service:8080
            predicates:
              - Path=/api/v1/auth/**, /api/v1/permissions/**
            filters:
              - AddRequestHeader=X-Request-Api-Key, ${API_KEY}
              - AddRequestHeader=X-Request-Source, EXTERNAL
          # Booking Service
          - id: booking-service-route
            uri: http://booking-service:8080
            predicates:
              - Path=/api/v1/bookings/**
            filters:
              - AddRequestHeader=X-Request-Api-Key, ${API_KEY}
              - AddRequestHeader=X-Request-Source, EXTERNAL
          # Calendar Service
          - id: calendar-service-route
            uri: http://calendar-service:8080
            predicates:
              - Path=/api/v1/calendars/**
            filters:
              - AddRequestHeader=X-Request-Api-Key, ${API_KEY}
              - AddRequestHeader=X-Request-Source, EXTERNAL
          # User Service
          - id: user-service-route
            uri: http://user-service:8080
            predicates:
              - Path=/api/v1/users/**
            filters:
              - AddRequestHeader=X-Request-Api-Key, ${API_KEY}
              - AddRequestHeader=X-Request-Source, EXTERNAL
          # Account Service
          - id: account-service-route
            uri: http://account-service:8080
            predicates:
              - Path=/api/v1/accounts/**
            filters:
              - AddRequestHeader=X-Request-Api-Key, ${API_KEY}
              - AddRequestHeader=X-Request-Source, EXTERNAL

          - id: department-service
            uri: http://department-service:8080
            predicates:
              - Path=/api/v1/departments/**
            filters:
              - AddRequestHeader=X-Request-Api-Key, ${API_KEY}
              - AddRequestHeader=X-Request-Source, EXTERNAL
#jwt:
#  auth:
#    converter:
#      resource-id: plahctoh-realm

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

feign:
  clients:
    auth-service:
      url: "${AUTH_SERVICE_URL}"
    department-service:
      url: "${DEPARTMENT_SERVICE_URL}"

http-configuration:
  security:
    filters:
      get-user-header-filter:
        enable: false
      api-key-header-filter:
        enable: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

