spring:
  application:
    name: "user-service"
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-user-master.yaml
    enabled: true
  datasource:
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/}${DATABASE_NAME:barber-shop-database}
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    properties:
      hibernate:
        show_sql: true
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always