spring:
  application:
    name: "user-service"
    security:
      jwt:
        access-key:
          value: ${ACCESS_KEY}
        refresh-key:
          value: ${REFRESH_KEY}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-user-master.yaml
    enabled: true
    default-schema: user_service_schema
  datasource:
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/}${DATABASE_NAME:plahctoh-database}
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    properties:
      hibernate:
        show_sql: true
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
feign:
  clients:
    user-credentials-service:
      url: "${AUTH_SERVICE_URL}"