dependencies {
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
    implementation "io.jsonwebtoken:jjwt-api:${jwtVersion}"
    implementation "io.jsonwebtoken:jjwt-impl:${jwtVersion}"
    implementation "io.jsonwebtoken:jjwt-gson:${jwtVersion}"
    implementation project(":libs.common:auth")
    implementation project(":libs.common:department")
    implementation project(":libs.common:notification")
    implementation project(":libs.common:user")
    implementation project(":libs.common:property-source-scanner")
}
