server:
  port: 8083

spring:
  application:
    name: booking
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: false

feign:
  clients:
    user-client:
      url: ""