server:
  port: 8083

spring:
  application:
    name: booking
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: false
  datasource:
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/barber-shop-database
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        show_sql: true

feign:
  clients:
    user-client:
      url: "http://${USER_SERVICE_NAMESPACE:localhost}:${USER_SERVICE_PORT:9001}/${USER_SERVICE_URL:api/v1/user}"
      get-user:
        url: "${USER_SERVICE_GET_USER_URL:/{userId}}"
    procedure-client:
      url: "http://${PROCEDURE_SERVICE_NAMESPACE:localhost}:${PROCEDURE_SERVICE_PORT:9002}/${PROCEDURE_SERVICE_URL:api/v1/procedures}"
      get-procedure:
        url: "${PROCEDURE_SERVICE_GET_PROCEDURE_URL:/{procedureId}}"