dependencies {
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.cloud:spring-cloud-starter-openfeign"
    annotationProcessor 'org.projectlombok:lombok'
    compileOnly "org.projectlombok:lombok"
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = "eu.senla.libs"
            artifactId = "http-configuration-core"
            version = "1.0.0"
            from components.java
        }
    }
}