input {
    file {
        path => "/app/logs/service.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"
    }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-%{+YYYY.MM.dd}"
    user => "elastic"
    password => "XNV1iC2BZ7alheRmqo1_"
  }
  stdout {
    codec => rubydebug
  }
}
