dependencies {
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
    implementation project(":libs.common:account")
    implementation project(":libs.common:department")
    implementation project(":libs.common:user")
    implementation project(":libs.common:auth")
}