spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIGS_URL:https://github.com/BigBearBalls/barber-shop-project}
          default-label: Artem-dev
          search-paths: configs

server:
  port: 8888